version: "3.9"
services:
  app:
    container_name: participation_rate
    build: 
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: mysql://user1:password@db_pp:3306/pp_rate
      DELAY: 10
      RUST_BACKTRACE: 1
    ports:
      - "8080:8080"
    depends_on:
      - db_pp
  db_pp:
    container_name: db_pp
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pp_rate
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'